"""
OSagnent Agent Generator
========================
Converts learned task patterns into Hermes skill files.

Input: pattern_engine output
Output: ~/.hermes/skills/<task_name>/SKILL.md + scripts/

Confidence thresholds:
  95%+ → autonomous execution
  80-95% → execute + flag uncertainties  
  60-80% → show plan before execution
  <60% → ask human before proceeding
"""
from __future__ import annotations
import json, hashlib
from pathlib import Path
from typing import Optional

SKILL_DIR = Path.home() / ".hermes" / "skills"

def task_to_skill_name(task: dict) -> str:
    tools = task.get("tools_used", [])
    if tools:
        return f"osagnent_{tools[0]}"
    return f"osagnent_task_{task['id']}"

def generate_skill_md(task: dict, worker_id: str) -> str:
    conf = task.get("confidence", 0.5)
    if conf >= 0.95:
        autonomy = "## Autonomy Level: FULL — AI executes autonomously, notifies on completion"
    elif conf >= 0.80:
        autonomy = "## Autonomy Level: HIGH — AI executes, flags uncertainties for review"
    elif conf >= 0.60:
        autonomy = "## Autonomy Level: MODERATE — AI shows plan before execution, seeks approval on uncertainties"
    else:
        autonomy = "## Autonomy Level: LOW — AI asks human before proceeding on each step"
    
    tools_list = "\n".join(f"- `{t}`" for t in task.get("tools_used", []))
    steps_md = "\n".join(f"{i+1}. `{s['tool']}` — args: `{json.dumps(s['args'])[:100]}`" 
                         for i, s in enumerate(task.get("steps", [])))
    
    return f"""---
name: {task_to_skill_name(task)}
description: OSagnent learned skill for worker {worker_id} — {task.get('frequency', 0)}x observed
compatibility: Hermes Agent v0.13+
---

# {task.get('id', 'task')} — Learned from {worker_id}

{autonomy}
Confidence: {conf*100:.0f}% | Frequency: {task.get('frequency', 0)}x observed

## What This Task Does

Observed {task.get('frequency', 0)} times. Performs the following sequence of tool calls:

## Tools Used
{tools_list}

## Observed Steps

{steps_md}

## Human Approval Checkpoints

Confidence is {conf*100:.0f}%. {"Human approval NOT required — autonomous execution." if conf >= 0.95 else "Flag for human review at each step completion." if conf >= 0.80 else "Require human approval before starting."}

## Implementation Notes

Auto-generated by OSagnent from observation data.
Do not edit manually — changes will be overwritten on next observation cycle.
"""

def generate_skill_tool(task: dict) -> str:
    """Generate the Hermes skill tool script for executing this task."""
    steps = task.get("steps", [])
    steps_code = "\n".join(f'    {{"tool": "{s["tool"]}", "args": {json.dumps(s["args"])}}},' for s in steps)
    
    return f'''"""
OSagnent Skill Tool: {task["id"]}
Auto-generated — do not edit manually
"""
from __future__ import annotations

def execute_{task["id"].replace("-", "_")}(context):
    """
    Execute {task["id"]} — confidence {task.get("confidence", 0.5)*100:.0f}%
    Observed {task.get("frequency", 0)} times
    """
    steps = [
{steps_code}
    ]
    
    results = []
    for step in steps:
        result = context.call_tool(step["tool"], step["args"])
        results.append(result)
        # Confidence-based checkpoint
        conf = {task.get("confidence", 0.5)}
        if conf < 0.95:
            if conf < 0.80:
                context.ask_human_approval(f"Step {{step['tool']}} done. Continue?")
            else:
                context.flag_uncertainty(step["tool"], result)
    
    return results
'''

def generate_skill(task: dict, worker_id: str) -> dict:
    skill_name = task_to_skill_name(task)
    skill_path = SKILL_DIR / skill_name
    skill_path.mkdir(parents=True, exist_ok=True)
    
    # Write SKILL.md
    (skill_path / "SKILL.md").write_text(generate_skill_md(task, worker_id))
    
    # Write skill tool
    (skill_path / "skill_tool.py").write_text(generate_skill_tool(task))
    
    return {"skill_name": skill_name, "path": str(skill_path)}

def generate_all_skills(worker_id: str) -> list[dict]:
    from .pattern_engine import get_top_tasks
    tasks = get_top_tasks(worker_id, 20)
    return [generate_skill(t, worker_id) for t in tasks]
