"""Generates Hermes SKILL.md from learned patterns."""
import json
from pathlib import Path
from typing import Optional
import here

SKILL_TEMPLATE = """---
name: {name}
description: {description}
compatibility: Hermes Agent v0.13+
---

# {name}

{description}

## When to Use
{when_to_use}

## How to Use
{how_to_use}

## Notes
Auto-generated by OSagnent from {sample_count} observations.
Confidence: {confidence:.0%}
Last updated: {timestamp}
"""

class SkillGenerator:
    """Generates Hermes SKILL.md files from learned patterns."""
    
    def __init__(self, skills_dir: str = "~/.hermes/skills"):
        self.skills_dir = Path(skills_dir).expanduser()
        self.here = here
    
    def generate(self, pattern: dict, dry_run: bool = False) -> str:
        """Generate a SKILL.md from a pattern spec."""
        skill_content = SKILL_TEMPLATE.format(
            name=pattern.get("name", "unnamed_skill"),
            description=pattern.get("description", "Auto-generated skill"),
            when_to_use=pattern.get("trigger", "When needed"),
            how_to_use=pattern.get("action", "Execute the learned workflow"),
            sample_count=pattern.get("sample_count", 0),
            confidence=pattern.get("confidence", 0.0),
            timestamp=pattern.get("timestamp", ""),
        )
        
        if dry_run:
            return skill_content
        
        # Write to skills directory
        skill_name = pattern["name"]
        skill_dir = self.skills_dir / skill_name
        skill_dir.mkdir(exist_ok=True, parents=True)
        
        skill_file = skill_dir / "SKILL.md"
        skill_file.write_text(skill_content)
        
        # Write metadata
        meta_file = skill_dir / "osagnent_meta.json"
        meta_file.write_text(json.dumps(pattern, indent=2))
        
        return skill_content
    
    def list_generated_skills(self) -> list[dict]:
        """List all skills generated by OSagnent."""
        skills = []
        for skill_dir in self.skills_dir.iterdir():
            if not skill_dir.is_dir():
                continue
            meta_file = skill_dir / "osagnent_meta.json"
            if meta_file.exists():
                skills.append(json.loads(meta_file.read_text()))
        return skills
    
    def delete(self, skill_name: str):
        """Delete an auto-generated skill."""
        skill_dir = self.skills_dir / skill_name
        if skill_dir.exists():
            import shutil
            shutil.rmtree(skill_dir)
            print(f"Deleted skill: {skill_name}")
    
    def improve_from_feedback(self, skill_name: str, feedback: dict):
        """Refine a skill based on human feedback."""
        skill_dir = self.skills_dir / skill_name
        meta_file = skill_dir / "osagnent_meta.json"
        
        if meta_file.exists():
            meta = json.loads(meta_file.read_text())
            meta["feedback_count"] = meta.get("feedback_count", 0) + 1
            meta["corrections"] = meta.get("corrections", []) + [feedback]
            meta["confidence"] = min(0.99, meta.get("confidence", 0.8) + 0.05)
            meta["timestamp"] = datetime.now().isoformat()
            meta_file.write_text(json.dumps(meta, indent=2))
            
            # Regenerate the skill
            self.generate(meta)
            print(f"Improved skill: {skill_name} → confidence now {meta['confidence']:.0%}")
