#!/bin/bash
set -e
echo "Forking all repos to your GitHub account..."
echo "Run 'gh auth login' first if not already authenticated."

REPOS=(
  "github/spec-kit"
  "agentscope-ai/ReMe"
  "mutonby/openshorts"
  "jamiepine/voicebox"
  "RightNow-AI/picolm"
  "openbotx/openbotx"
  "public-apis/public-apis"
  "public-apis/ytdownloader"
  "gsd-build/get-shit-done"
  "vinceliuice/orchis"
  "Helixar-AI/ReleaseGuard"
  "marcusschwarz/MoneyPrinterTurbo"
  "NVIDIA/NemoClaw"
  "HKUDS/ClawTeam"
  "cantino/huginn"
  "public-apis/claude-code-game-studio"
  "vinceliuice/localopensourcelist"
  "public-apis/pinzhudownloader"
  "gptscript-pkg/gptscript-mcp"
  "PrefectHQ/prefect"
  "laudspeaker/laudspeaker"
  "SWE-agent/mini-swe-agent"
  "SWE-agent/swe-agent"
  "frectonz/penny"
  "frectonz/cli-anything"
  "browser-use/browser-use"
  "iii-hq/agentos"
  "marcusschwarz0/awesome-llm-apps"
  "bigskysoftware/htmx-extensions"
  "kxlash/windsurf-skills"
  "HINChley/growth-skills"
  "obra/superpowers"
  "gsd-build/get-shit-done"
  "fynnfluegge/agtx"
  "PrefectHQ/avoid-slop"
  "louisho5/picobot"
  "pinchtab/pinchtab"
  "cisco-ai-defense/skill-scanner"
  "TauricResearch/TradingAgents"
)

for repo in "${REPOS[@]}"; do
  echo "Forking $repo..."
  gh repo fork "$repo" --clone 2>/dev/null || echo "  ⚠ Skipped (already forked or unavailable)"
done
echo "=== All repos forked ==="
